name: CI

on:
  push:
    branches:
      - master

jobs:
  unit_test:
    name: Run unit tests with Karma and Jasmine
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Clean npm cache
      run: npm cache clean --force
    - name: Install dependencies
      run: cd openvidu-call-front && npm install
    - name: Unit Tests
      run: cd openvidu-call-front && npm run test